name: meu_querido_livro
description: Flutter app to register books.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.3.2+2
  qr_flutter: ^3.2.0
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  photo_view: ^0.10.2
  asuka: ^1.0.4
  image_picker: ^0.6.7+7
  image_cropper: ^1.3.1
  shared_preferences: ^0.5.12
  flutter_slidable: ^0.5.7


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/escola.png
    - assets/images/splash-imge.jpeg
    - assets/images/biblioteca.png
    - assets/images/livro.png
    - assets/images/anao.png
    - assets/images/brasil.jpg
    - assets/images/usa.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
